In [50]:
!pip install numpy

In [51]:
# Generate 5x5 random matrix.
# Generate 10 random integers between 50-100.
import numpy as np

random_matrix = np.random.rand(5, 5)
print(f"5x5 Random Matrix:\n{random_matrix}")


random_integers = np.random.randint(50, 101, size=10)
print(f"\n10 Random Integers between 50 and 100: {random_integers}")


5x5 Random Matrix:
[[0.85499658 0.40329534 0.55789272 0.88076375 0.72646977]
 [0.35938717 0.19747917 0.62461391 0.30550529 0.46610137]
 [0.58575723 0.37188947 0.40297061 0.9132915  0.56509813]
 [0.06016523 0.63711058 0.35204167 0.40926871 0.58243785]
 [0.36832249 0.98672971 0.43146942 0.90689854 0.87303531]]

10 Random Integers between 50 and 100: [ 58  73  80  98  91 100  94  88  60  52]


In [52]:
!pip install pandas

In [53]:
import pandas as pd

In [54]:
df = pd.read_csv('D:\\projects\\DEPI-Microsoft-AI-Engineer\\datasets\\employees.csv')



In [55]:
df.head()

ID           Name Department  Age  Salary Joining_Date
0   1       John Doe         HR   28   50000   2020-05-21
1   2     Jane Smith         IT   34   75000   2019-06-12
2   3    Bob Johnson    Finance   45   85000   2018-07-15
3   4    Alice White         IT   29   72000   2021-01-04
4   5  Charlie Brown  Marketing   32   68000   2019-11-30

In [56]:
salaryByAge = df.groupby('Age')['Salary'].mean()
print("Average Salary by Age:")
print(salaryByAge)

Average Salary by Age:
Age
26    64000.0
28    50000.0
29    72000.0
30    55000.0
32    68000.0
34    75000.0
38    70000.0
41    54000.0
45    85000.0
50    90000.0
Name: Salary, dtype: float64


In [57]:
df.describe()

ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  35.300000  68300.000000
std     3.02765   7.958922  13106.826042
min     1.00000  26.000000  50000.000000
25%     3.25000  29.250000  57250.000000
50%     5.50000  33.000000  69000.000000
75%     7.75000  40.250000  74250.000000
max    10.00000  50.000000  90000.000000

In [58]:
# salary > 4000 , age < 30
mask = (df['Salary'] > 4000) & (df['Age']<30)

df[mask]

ID          Name Department  Age  Salary Joining_Date
0   1      John Doe         HR   28   50000   2020-05-21
3   4   Alice White         IT   29   72000   2021-01-04
7   8  Linda Taylor         IT   26   64000   2022-02-10

In [59]:
mask = (df['Department']=="IT") & (df['Salary']>60000)
df[mask]

ID          Name Department  Age  Salary Joining_Date
1   2    Jane Smith         IT   34   75000   2019-06-12
3   4   Alice White         IT   29   72000   2021-01-04
7   8  Linda Taylor         IT   26   64000   2022-02-10

In [60]:
df['Bonus'] = df['Salary']*.1
df.head()

ID           Name Department  Age  Salary Joining_Date   Bonus
0   1       John Doe         HR   28   50000   2020-05-21  5000.0
1   2     Jane Smith         IT   34   75000   2019-06-12  7500.0
2   3    Bob Johnson    Finance   45   85000   2018-07-15  8500.0
3   4    Alice White         IT   29   72000   2021-01-04  7200.0
4   5  Charlie Brown  Marketing   32   68000   2019-11-30  6800.0

In [61]:
# Filter employees with salary > 5000.
salary_mask = df['Salary'] > 5000

# Add new column "Tax" = 15% of salary.
df['Tax'] = df['Salary'] * 0.15

# Increase salary by 1000 for filtered employees.
df.loc[salary_mask, 'Salary'] = df.loc[salary_mask, 'Salary'] + 1000

# Show only Name + Tax columns for filtered employees.
df.loc[salary_mask, ['Name', 'Tax']]


Name      Tax
0       John Doe   7500.0
1     Jane Smith  11250.0
2    Bob Johnson  12750.0
3    Alice White  10800.0
4  Charlie Brown  10200.0
5      Eva Green   8100.0
6     Mike Davis  13500.0
7   Linda Taylor   9600.0
8   James Wilson  10500.0
9    Sarah Adams   8250.0

In [62]:

avg_age_by_department = df.groupby('Department')['Age'].mean()
print("Average Age by Department:")
print(avg_age_by_department)

avg_bonus_by_age_group = df.groupby('Age')['Bonus'].mean()
print("\nAverage Bonus by Age Group:")
print(avg_bonus_by_age_group)

df['Joining_Date'] = pd.to_datetime(df['Joining_Date'])
hires_by_year = df.groupby(df['Joining_Date'].dt.year)['Name'].count()
print("\nHires by Year:")
print(hires_by_year)


Average Age by Department:
Department
Finance      47.500000
HR           33.000000
IT           29.666667
Marketing    35.000000
Name: Age, dtype: float64

Average Bonus by Age Group:
Age
26    6400.0
28    5000.0
29    7200.0
30    5500.0
32    6800.0
34    7500.0
38    7000.0
41    5400.0
45    8500.0
50    9000.0
Name: Bonus, dtype: float64

Hires by Year:
Joining_Date
2016    1
2017    1
2018    1
2019    2
2020    2
2021    2
2022    1
Name: Name, dtype: int64


In [63]:
df['Quarter'] = df['Joining_Date'].dt.to_period('Q')
hires_by_quarter = df.groupby('Quarter')['Name'].count()
print("\nHires by Quarter:")
print(hires_by_quarter)


Hires by Quarter:
Quarter
2016Q3    1
2017Q2    1
2018Q3    1
2019Q2    1
2019Q4    1
2020Q2    1
2020Q3    1
2021Q1    2
2022Q1    1
Freq: Q-DEC, Name: Name, dtype: int64


In [64]:
# based on department
# min salary / avg bouns / avg age
avg_stats_by_department = df.groupby('Department').agg({
    'Salary': 'min',
    'Bonus': 'mean',
    'Age': 'mean'
})
print("\nAverage Stats by Department:")
print(avg_stats_by_department)




Average Stats by Department:
            Salary        Bonus        Age
Department                                
Finance      86000  8750.000000  47.500000
HR           51000  5300.000000  33.000000
IT           65000  7033.333333  29.666667
Marketing    69000  6900.000000  35.000000


In [65]:
age=df.groupby('Age')
salary = age['Salary']
print("Average Salary by Age:")
print(salary.mean())

Average Salary by Age:
Age
26    65000.0
28    51000.0
29    73000.0
30    56000.0
32    69000.0
34    76000.0
38    71000.0
41    55000.0
45    86000.0
50    91000.0
Name: Salary, dtype: float64


In [66]:
df['Joining_Date'] = pd.to_datetime(df['Joining_Date'])
HiresByYear = df.groupby(df['Joining_Date'].dt.year)['Name'].count()
print("Hires by Year:")
print(HiresByYear)



dates = df['Joining_Date']
years = dates.dt.year
g = df.groupby(years)
hires_by_year = g['Name'].count()
print("Hires by Year:")
print(hires_by_year)

Hires by Year:
Joining_Date
2016    1
2017    1
2018    1
2019    2
2020    2
2021    2
2022    1
Name: Name, dtype: int64
Hires by Year:
Joining_Date
2016    1
2017    1
2018    1
2019    2
2020    2
2021    2
2022    1
Name: Name, dtype: int64


In [67]:
# pivot table
# max slary per dep
# count emp per dep

pivot = df.pivot_table(index='Department', values='Salary', aggfunc='max')
print("Max Salary per Department:")
print(pivot)


Max Salary per Department:
            Salary
Department        
Finance      91000
HR           56000
IT           76000
Marketing    71000


In [70]:
#مجموع الحوافز اللى طلع لكل قسم على مدار اجزاء السنه 

pd.pivot_table(
    df,
    values='Salary',
    index='Department',
    columns='Quarter',
    aggfunc='mean',
    fill_value=0)

Quarter      2016Q3   2017Q2   2018Q3   2019Q2   2019Q4   2020Q2   2020Q3  \
Department                                                                  
Finance     91000.0      0.0  86000.0      0.0      0.0      0.0      0.0   
HR              0.0  55000.0      0.0      0.0      0.0  51000.0      0.0   
IT              0.0      0.0      0.0  76000.0      0.0      0.0      0.0   
Marketing       0.0      0.0      0.0      0.0  69000.0      0.0  71000.0   

Quarter      2021Q1   2022Q1  
Department                    
Finance         0.0      0.0  
HR          56000.0      0.0  
IT          73000.0  65000.0  
Marketing       0.0      0.0